### PR TITLE
Spell fix

### PR DESCRIPTION
**Pull request by rkiyanchuk**

### CODE REVIEW

**Review by brhx — APPROVED** [review]
Hah thank you for the easy review process, LGTM! 👍

**Review by Landrash — APPROVED** [review]
Spelling.. why is it so hard :sob:

**Comment by rkiyanchuk** [comment]
@Landrash That's what makes us humans I guess :smile:

Maybe doing the whole PR over single typo was a bit of an overhead, but thought it would make reading even more pleasant for others :)

Just starting with home-assistant and am very excited, but can only offer proofreading of docs so far, though hopefully I'll get to bug fixes/features as well :)

Thanks for the merge! :+1:

**Comment by Landrash** [comment]
I never complain about pr's small or big.

Good luck and if your in a proofreading mode there's a couple of hundred pages of components also 😅

**Pull request merged**
